- hosts: 127.0.0.1
  tasks:
    - name: "apply Namespace"
      kubernetes.core.k8s:
        src: manifests/namespaces/zabbix-ns.yml
    - name: "apply ConfigMap & Secrets"
      kubernetes.core.k8s:
        src: manifests/configmaps/zabbix-mysql-cfg.yml
    - name: "apply MySQL DB volume"
      kubernetes.core.k8s:
        src: manifests/volumes/zabbix-mysql-pv.yml
    - name: "apply MySQL deployment"
      kubernetes.core.k8s:
        src: manifests/workloads/zabbix-mysql-sts.yml
    - name: "apply MySQL service"
      kubernetes.core.k8s:
        src: manifests/services/zabbix-mysql-svc.yml
    - name: "apply Zabbix server deployment"
      kubernetes.core.k8s:
        src: manifests/workloads/zabbix-server-dep.yml
    - name: "apply Zabbix server service"
      kubernetes.core.k8s:
        src: manifests/services/zabbix-server-svc.yml
    - name: "apply Zabbix web control panel deployment"
      kubernetes.core.k8s:
        src: manifests/workloads/zabbix-web-dep.yml
    - name: "apply Zabbix web control panel service"
      kubernetes.core.k8s:
        src: manifests/services/zabbix-web-svc.yml
